ADD JAR /usr/lib/hive-hcatalog/share/hcatalog/hive-hcatalog-core-1.1.0-cdh5.8.0.jar;
INSERT OVERWRITE TABLE observation_flat SELECT 
    CAST(unix_timestamp(issue_time_utc, "yyyy-MM-dd'T'HH:mm:ss'Z'")*1000 AS TIMESTAMP) as issue_timestamp, 
    issue_time_local, 
    -- period
    CAST(unix_timestamp(period.time_utc, "yyyy-MM-dd'T'HH:mm:ss'Z'")*1000 AS TIMESTAMP) as period_timestamp, 
    period.time_local as period_time_local,
    -- station
    station.bom_id as stn_bom_id, 
    station.description as stn_description, 
    station.forecast_district_id as stn_forecast_district_id, 
    CAST(station.lat  as FLOAT) as stn_lat, CAST(station.lon as FLOAT) as stn_lon, 
    station.stn_name as stn_name,
    station.tz as stn_tz,
    station.wmo_id as stn_wmo_id,
    -- elements
    CAST(elements.air_temperature as FLOAT) as air_temperature, 
    CAST(elements.apparent_temp as FLOAT) as apparent_temp  ,
    elements.cloud  as cloud    ,
    CAST(elements.cloud_base_m as INT) AS cloud_base_m,
    CAST(elements.cloud_oktas AS INT) AS cloud_oktas,
    elements.cloud_type_id  AS cloud_type_id,
    CAST(elements.delta_t AS FLOAT) as delta_t,
    CAST(elements.dew_point AS FLOAT) as dew_point,
    CAST(elements.gust_kmh as INT) as gust_kmh,
    CAST(elements.maximum_air_temperature as FLOAT) as maximum_air_temperature,
    elements.maximum_gust_dir as maximum_gust_dir   ,
    CAST(elements.maximum_gust_kmh as INT) as maximum_gust_kmh  ,
    CAST(elements.maximum_gust_spd as INT) as maximum_gust_spd  ,
    CAST(elements.minimum_air_temperature as FLOAT) as minimum_air_temperature  ,
    CAST(elements.msl_pres as FLOAT) as msl_pres    ,
    CAST(elements.pres as FLOAT) as pres    ,
    CAST(elements.qnh_pres as FLOAT) as qnh_pres    ,
    CAST(elements.rainfall as FLOAT) as rainfall    ,
    CAST(elements.rainfall_24hr as FLOAT) as rainfall_24hr,
    CAST(elements.rel_humidity as INT) as rel_humidity,
    CAST(elements.sea_height as INT) as sea_height,
    elements.swell_dir  as swell_dir,
    CAST(elements.swell_height as INT) as swell_height,
    CAST(elements.swell_period as INT) as swell_period,
    CAST(elements.vis_km as INT) as vis_km,
    elements.weather as weather,
    elements.wind_dir as wind_dir,
    CAST(elements.wind_dir_deg as INT) as wind_dir_deg,
    CAST(elements.wind_gust_spd as INT) as wind_gust_spd,
    CAST(elements.wind_spd as INT) as wind_spd,
    CAST(elements.wind_spd_kmh as INT) as wind_spd_kmh
FROM observation_ext;